### ISSUE TITLE
关于router

### ISSUE THREAD

**Issue by ahlixinjie** [langyanduan/Reborn#2]
我在router字段这么写
[ROUTER]
geoip:
  cn: direct
  hk: direct
  tw: direct
default: ss

这样台湾和香港的ip可以直连么?

还是应该这样写:
[ROUTER]
geoip:
  cn, hk, tw: direct
default: ss

**Comment by langyanduan** [comment]
第一种写法

```
[ROUTER]
geoip:
  cn: direct
  hk: direct
  tw: reject
default: ss
```
