### ISSUE TITLE
Shadowsocks-libev 作为后端时，socks5 模式出错

### ISSUE THREAD

**Issue by hguandl** [langyanduan/Reborn#3]
## 环境
* macOS 10.13.3 (17D47)
* [Reborn v0.4.2](https://github.com/langyanduan/Reborn/releases/tag/0.4.2)
* [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev) 3.1.3

## 配置
```yaml
[PROXY]
- name: local
  server: 127.0.0.1
  port: 2048
  timeout: 600
  type: socks5

[ROUTER]
geoip:
  cn: direct
default: local


[DNS]
server: system
```

## 预期效果
`ss-local` 作为后端运行，监听 2048 端口；`Reborn.app`使用 2048 端口的 socks5 代理工作。

## 实际效果
使用出错，无法访问网页。在 `ss-local` 的日志里显示不断访问代理服务器的 IP，直到其崩溃。

### 截图
![demo-0001](https://user-images.githubusercontent.com/10684225/35925752-7d33d874-0c61-11e8-8eb9-b3d905424710.jpg)
![demo-0002](https://user-images.githubusercontent.com/10684225/35925767-84d7741e-0c61-11e8-8225-436c734daea8.jpg)
### 日志
[XLogs.zip](https://github.com/langyanduan/Reborn/files/1703730/XLogs.zip)
### 视频 Demo
[demo.zip](https://github.com/langyanduan/Reborn/files/1703778/demo.zip)

**Comment by langyanduan** [comment]
这个是因为 `ss-local` 的网络也被 reborn 接管了，造成了递归。可以配置进程规则来规避。v0.4.2 已经支持进程规则，不过进程名大小写敏感，下版本会改成大小写不敏感。

把配置文件改成下面这样，

```
[PROXY]
- name: local
  server: 127.0.0.1
  port: 2048
  timeout: 600
  type: socks5

[ROUTER]
geoip:
  cn: direct
process:
  ss-local: direct
default: local

[DNS]
server: system
```
